include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 launch carla_its_adapter carla_its_adapter_node_launch.launch.py
  TARGET: dev,run
  PLATFORM: amd64
  ENABLE_INDUSTRIAL_CI: 'true'