/**:
  ros__parameters:
    map_server_name: /ll2_map_server      # Name of map server
    set_ll2_map_from_carla: true          # Automatically the ll2 map based on the CARLA map
    set_ll2_origin_from_carla: true       # Automatically set the origin of the ll2 map based on the CARLA map

    carla_fixed_frame_id: carla_map       # Name of the fixed frame id in CARLA
    fixed_frame_id: map                   # Name of the fixed frame id over time
    carla_vehicle_frame_id: ego_vehicle   # Name of the vehicle frame id in CARLA
    vehicle_frame_id: geo_center          # Name of the vehicle frame id.
    carla_vehicle_frame_id_to_vehicle_frame_id: 0.0   # Longitudinal offset from carla_vehicle_frame_id to vehicle_frame_id
