<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>simulation_adapter</name>
  <version>1.4.0</version>
  <description>Adapts OpenADSim data to OpenADStack-compatible ROS 2 interfaces</description>

  <maintainer email="christian.geller@ika.rwth-aachen.de">Christian Geller</maintainer>
  <author email="christian.geller@ika.rwth-aachen.de">Christian Geller</author>
  <author email="guido.linden@ika.rwth-aachen.de">Guido Linden</author>
  <author email="jean-pierre.busch@ika.rwth-aachen.de">Jean-Pierre Busch</author>
  <author email="silas.damaschke@ika.rwth-aachen.de">Silas Damaschke</author>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>perception_msgs</depend>
  <depend>perception_msgs_utils</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_perception_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_trajectory_planning_msgs</depend>
  <depend>trajectory_planning_msgs</depend>
  <depend>trajectory_planning_msgs_utils</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_clang_tidy</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
