openadservice:
  name: simulation-adapter
  image: ghcr.io/openads-project/simulation_adapter:v1.4.0
  env:
    # --- name ------
    NAMESPACE: /
    NAME: simulation_adapter
    # --- inputs ----
    INPUT_MAP_INFO_TOPIC: ~/input_map_info
    INPUT_EGO_DATA_TOPIC: ~/input_ego_data
    INPUT_OBJECT_LIST_TOPIC: ~/input_object_list
    INPUT_TRAJECTORY_TOPIC: ~/input_trajectory
    # --- outputs ---
    OUTPUT_EGO_DATA_TOPIC: ~/ego_data
    OUTPUT_OBJECT_LIST_TOPIC: ~/object_list
    OUTPUT_OBJECT_LIST_FIXED_TOPIC: ~/object_list_fixed
    OUTPUT_EGO_IMU_TOPIC: ~/ego_imu
    OUTPUT_EGO_ODOMETRY_TOPIC: ~/ego_odometry
    OUTPUT_EGO_VEHICLE_STATE_TOPIC: ~/ego_vehicle_state
    # --- other -----
    LOG_LEVEL: info
    USE_SIM_TIME: true
    PARAMS: /docker-ros/ws/install/simulation_adapter/share/simulation_adapter/config/params.yml
    LOAD_LANELET_MAP: true
  args:
  - /bin/bash
  - -ic
  - |
    ros2 launch simulation_adapter simulation_adapter.launch.py \
      namespace:=${NAMESPACE} \
      name:=${NAME} \
      log_level:=${LOG_LEVEL} \
      use_sim_time:=${USE_SIM_TIME} \
      params:=${PARAMS} \
      load_lanelet_map:=${LOAD_LANELET_MAP} \
      input_map_info_topic:=${INPUT_MAP_INFO_TOPIC} \
      input_ego_data_topic:=${INPUT_EGO_DATA_TOPIC} \
      input_object_list_topic:=${INPUT_OBJECT_LIST_TOPIC} \
      input_trajectory_topic:=${INPUT_TRAJECTORY_TOPIC} \
      output_ego_data_topic:=${OUTPUT_EGO_DATA_TOPIC} \
      output_object_list_topic:=${OUTPUT_OBJECT_LIST_TOPIC} \
      output_object_list_fixed_topic:=${OUTPUT_OBJECT_LIST_FIXED_TOPIC} \
      output_ego_imu_topic:=${OUTPUT_EGO_IMU_TOPIC} \
      output_ego_odometry_topic:=${OUTPUT_EGO_ODOMETRY_TOPIC} \
      output_ego_vehicle_state_topic:=${OUTPUT_EGO_VEHICLE_STATE_TOPIC}
  rosParamFileMountPath: /docker-ros/ws/install/simulation_adapter/share/simulation_adapter/config/params.yml
  rosParamFileData: null
